name: standardjs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  standard:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npx standard --verbose | npx snazzy
